In [110]:
import numpy as np 
import pandas as pd
from matplotlib import pyplot as plt

In [111]:
df=pd.read_csv('/kaggle/input/nn-from-scratch-1/train 2.csv')

preprocessing the data

In [112]:
df.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [113]:
df.describe()

label   pixel0   pixel1   pixel2   pixel3   pixel4   pixel5  \
count  42000.000000  42000.0  42000.0  42000.0  42000.0  42000.0  42000.0   
mean       4.456643      0.0      0.0      0.0      0.0      0.0      0.0   
std        2.887730      0.0      0.0      0.0      0.0      0.0      0.0   
min        0.000000      0.0      0.0      0.0      0.0      0.0      0.0   
25%        2.000000      0.0      0.0      0.0      0.0      0.0      0.0   
50%        4.000000      0.0      0.0      0.0      0.0      0.0      0.0   
75%        7.000000      0.0      0.0      0.0      0.0      0.0      0.0   
max        9.000000      0.0      0.0      0.0      0.0      0.0      0.0   

        pixel6   pixel7   pixel8  ...      pixel774      pixel775  \
count  42000.0  42000.0  42000.0  ...  42000.000000  42000.000000   
mean       0.0      0.0      0.0  ...      0.219286      0.117095   
std        0.0      0.0      0.0  ...      6.312890      4.633819   
min        0.0      0.0      0.0  ...      0.000000      0.000000   
25%        0.0      0.0      0.0  ...      0.000000      0.000000   
50%        0.0      0.0      0.0  ...      0.000000      0.000000   
75%        0.0      0.0      0.0  ...      0.000000      0.000000   
max        0.0      0.0      0.0  ...    254.000000    254.000000   

           pixel776     pixel777      pixel778      pixel779  pixel780  \
count  42000.000000  42000.00000  42000.000000  42000.000000   42000.0   
mean       0.059024      0.02019      0.017238      0.002857       0.0   
std        3.274488      1.75987      1.894498      0.414264       0.0   
min        0.000000      0.00000      0.000000      0.000000       0.0   
25%        0.000000      0.00000      0.000000      0.000000       0.0   
50%        0.000000      0.00000      0.000000      0.000000       0.0   
75%        0.000000      0.00000      0.000000      0.000000       0.0   
max      253.000000    253.00000    254.000000     62.000000       0.0   

       pixel781  pixel782  pixel783  
count   42000.0   42000.0   42000.0  
mean        0.0       0.0       0.0  
std         0.0       0.0       0.0  
min         0.0       0.0       0.0  
25%         0.0       0.0       0.0  
50%         0.0       0.0       0.0  
75%         0.0       0.0       0.0  
max         0.0       0.0       0.0  

[8 rows x 785 columns]

In [114]:
df.isna().sum()

label       0
pixel0      0
pixel1      0
pixel2      0
pixel3      0
           ..
pixel779    0
pixel780    0
pixel781    0
pixel782    0
pixel783    0
Length: 785, dtype: int64

In [115]:
df=np.array(df)

Shuffling introduces randomness that prevents biased learning, basically prevents overfitting,if you train in batches,it can get biased to each class

In [116]:
m,n=df.shape
np.random.shuffle(df)
print(m,n)

42000 785


m= no of total images 
n = no of features (all individual pixel data) + 1 (label)

In [117]:
df_val_dataset = df[0:1000].T
Y_val = df_val_dataset[0]
X_val = df_val_dataset[1:n]
X_val=X_val/255.

making a validation dataset before training the model,here we adjust the hyperparameters and check if the model is actually learning and not overfitting,here i'm taking 2000 examples for validation dataset

taking transpose makes the df_val matrix such that now each column is an example , thus we now have a matrix of 785x2000

In [118]:
print(df_val_dataset.shape)

(785, 1000)


now we will train on the remaining data

In [119]:
df_train = df[1000:m].T


df_train.shape

(785, 41000)

In [120]:
Y_train=df_train[0]
X_train=df_train[1:n]
X_train=X_train/255.

In [121]:
print(Y_val)
print("///////////")
print(X_val)
print("///////////")
print(Y_train)
print("///////////")
print(X_train)


[6 4 4 5 5 4 1 1 3 1 3 0 1 7 7 8 4 5 4 1 3 8 0 2 8 4 6 5 5 6 5 0 4 0 9 1 2
 6 9 4 2 0 0 3 9 6 3 3 9 6 9 1 7 7 1 3 8 5 4 3 1 8 3 7 0 2 9 9 4 4 7 3 2 4
 2 4 6 8 2 7 0 4 7 0 9 5 0 6 5 7 2 7 5 6 7 7 9 1 0 4 6 1 1 3 0 5 8 1 1 3 5
 0 0 4 0 4 3 9 1 5 1 2 1 8 7 4 5 4 5 5 6 4 9 9 2 1 7 2 8 1 1 6 4 4 9 4 2 5
 8 0 6 3 2 6 5 0 6 3 3 6 0 4 6 1 4 0 1 7 0 8 5 2 7 7 3 9 2 5 5 0 5 6 2 9 1
 7 4 1 6 4 5 1 7 1 7 6 4 8 5 8 2 9 6 3 4 0 0 2 3 8 7 8 7 7 8 7 8 4 7 2 8 9
 9 0 1 4 5 2 0 1 3 4 2 1 0 5 4 3 0 1 1 9 6 1 4 9 9 3 3 9 7 5 0 6 7 9 2 1 6
 5 1 2 1 3 2 4 4 0 3 4 1 4 5 2 5 1 6 4 6 1 9 4 4 8 0 2 7 3 0 2 4 0 8 7 3 1
 4 2 1 6 0 8 7 9 6 2 5 3 4 6 7 7 2 9 7 1 2 7 5 5 0 4 4 3 9 7 6 3 4 8 4 4 4
 2 7 9 2 3 3 2 7 0 5 3 8 5 1 1 2 5 1 0 7 1 6 9 0 9 5 1 3 4 9 0 0 8 7 3 5 8
 6 8 1 6 7 0 3 4 8 7 3 2 8 0 0 4 1 2 1 6 9 9 9 6 2 0 5 1 1 4 3 7 6 9 3 6 5
 7 4 5 1 7 7 8 7 1 1 8 3 9 4 2 1 9 3 9 4 9 5 6 1 8 2 0 7 4 4 4 4 6 7 0 3 4
 7 7 6 6 9 5 9 8 9 8 7 7 1 7 8 1 3 2 2 2 0 7 6 1 7 5 3 0 6 6 2 2 4 2 3 6 9
 3 5 4 7 4 7 8 4 3 6 5 2 

Y_val/Y_train containss all the label info
X_val/X_train contains all the pixel data

In [122]:
pd.DataFrame(X_train).head()

0      1      2      3      4      5      6      7      8      9      ...  \
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   

   40990  40991  40992  40993  40994  40995  40996  40997  40998  40999  
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  

[5 rows x 41000 columns]

the data is now loaded,now we define the initilizing parameters

In [123]:
 def initialize_parameters():
     W1=np.random.rand(10,784) - 0.5
     b1=np.random.rand(10,1) - 0.5
     W2=np.random.rand(10,10) - 0.5
     b2=np.random.rand(10,1) - 0.5
     return W1,b1,W2,b2

w1=weight for first hidden layer,10 neurons,subtracting 0.5 so that the data is now centered at origin,this helps in avoiding a scenario when everything is 0(both w and b = 0),and all the neurons basically start learning the exact same things by picking up the exact same changes

w2=weight for the output layer connected to previous layer,the size is (current no of neurons,previous layer no of neurons)

In [124]:
def ReLu(Z):
    return np.maximum(0,Z)

i dont understand ReLu's purrpose fully,what does it mean to remove non linearity 

In [125]:
def softmax(Z):
    exp = np.exp(Z - np.max(Z))
    return exp / exp.sum(axis=0)


now defining forward propagation algo

In [126]:
def forward_prop(W1,b1,W2,b2,X):
    Z1=W1.dot(X) + b1
    A1=ReLu(Z1)
    Z2=W2.dot(A1) + b2
    A2=softmax(Z2)
    return Z1,A1,Z2,A2


In [127]:
def derivative_ReLu(Z):
    # if (Z > 0):
    #     return 1
    # else:
    #     return 0
    return Z > 0

we need to one hot encode our labels,we do this because it can create an error while computing the loss fucntion,we do this by basically making the correct label value as 1 and remaining else as 0,then we make a matrix of this,eg for label 2 , we make [0,0,1,0,0....,]  

In [128]:
def one_hot_encode(Y):
    arr=np.zeros((Y.size,Y.max()+1))
    arr[np.arange(Y.size),Y]=1
    arr=arr.T
    return arr



In [129]:
def back_propagation(Z1, A1, Z2, A2, W1, W2, X, Y):
    m = Y.size
    one_hot_Y = one_hot_encode(Y)
    
    dZ2 = A2 - one_hot_Y
    dW2 = 1/m * dZ2.dot(A1.T)
    db2 = 1/m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * derivative_ReLu(Z1)  
    dW1 = 1/m * dZ1.dot(X.T)
    db1 = 1/m * np.sum(dZ1)
    
    return dW1, db1, dW2, db2


In [130]:
def update_para(W1,b1,W2,b2,dW1,db1,dW2,db2,alpha):
    W1=W1-alpha*dW1
    b1=b1-alpha*db1
    W2=W2-alpha*dW2
    b2=b2-alpha*db2
    return W1,b1,W2,b2

    

In [131]:
def get_predictions(A2):
    return np.argmax(A2, axis=0)


def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size



def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = initialize_parameters()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = back_propagation(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_para(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2


In [132]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 0.10, 500)

Iteration:  0
[5 5 5 ... 5 2 5] [4 3 6 ... 1 4 5]
0.0873170731707317
Iteration:  10
[6 0 5 ... 5 7 6] [4 3 6 ... 1 4 5]
0.21529268292682927
Iteration:  20
[6 5 5 ... 1 7 5] [4 3 6 ... 1 4 5]
0.2936829268292683
Iteration:  30
[6 5 5 ... 1 7 5] [4 3 6 ... 1 4 5]
0.3580243902439024
Iteration:  40
[8 5 5 ... 1 7 5] [4 3 6 ... 1 4 5]
0.4161463414634146
Iteration:  50
[8 5 5 ... 1 7 5] [4 3 6 ... 1 4 5]
0.46375609756097563
Iteration:  60
[4 5 5 ... 1 7 5] [4 3 6 ... 1 4 5]
0.4997560975609756
Iteration:  70
[4 3 5 ... 1 7 5] [4 3 6 ... 1 4 5]
0.528
Iteration:  80
[4 3 5 ... 1 7 5] [4 3 6 ... 1 4 5]
0.5531219512195122
Iteration:  90
[4 3 5 ... 1 7 5] [4 3 6 ... 1 4 5]
0.5754634146341463
Iteration:  100
[4 3 5 ... 1 7 5] [4 3 6 ... 1 4 5]
0.5974878048780488
Iteration:  110
[4 3 5 ... 1 7 5] [4 3 6 ... 1 4 5]
0.616609756097561
Iteration:  120
[4 3 5 ... 1 9 5] [4 3 6 ... 1 4 5]
0.6351707317073171
Iteration:  130
[4 3 5 ... 1 9 5] [4 3 6 ... 1 4 5]
0.6543658536585366
Iteration:  140
[4 3 5 ... 1 

In [70]:
print("Now training for more iterations(1000) ")

Now training for more iterations(1000) 


In [65]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 0.10, 1000)

Iteration:  0
[6 6 6 ... 6 6 6] [0 5 5 ... 2 7 1]
0.11721951219512194
Iteration:  10
[5 5 7 ... 6 7 1] [0 5 5 ... 2 7 1]
0.22273170731707317
Iteration:  20
[0 5 7 ... 6 7 1] [0 5 5 ... 2 7 1]
0.320609756097561
Iteration:  30
[0 5 6 ... 7 7 1] [0 5 5 ... 2 7 1]
0.3838536585365854
Iteration:  40
[0 5 7 ... 7 7 8] [0 5 5 ... 2 7 1]
0.4484390243902439
Iteration:  50
[0 5 7 ... 2 7 1] [0 5 5 ... 2 7 1]
0.5095609756097561
Iteration:  60
[0 5 7 ... 2 7 1] [0 5 5 ... 2 7 1]
0.5594878048780488
Iteration:  70
[0 5 2 ... 2 7 1] [0 5 5 ... 2 7 1]
0.5968780487804878
Iteration:  80
[0 5 2 ... 2 7 1] [0 5 5 ... 2 7 1]
0.6244146341463415
Iteration:  90
[0 5 2 ... 2 7 1] [0 5 5 ... 2 7 1]
0.645390243902439
Iteration:  100
[0 5 2 ... 2 7 1] [0 5 5 ... 2 7 1]
0.6630487804878049
Iteration:  110
[0 5 2 ... 2 7 1] [0 5 5 ... 2 7 1]
0.6778536585365854
Iteration:  120
[0 5 2 ... 2 7 1] [0 5 5 ... 2 7 1]
0.6917073170731707
Iteration:  130
[0 5 2 ... 2 7 1] [0 5 5 ... 2 7 1]
0.7028292682926829
Iteration:  140
[

The model is now 88 percent accurate

Now trying it on the test dataset

In [87]:
df = pd.read_csv('/kaggle/input/nn-from-scratch-1/test 2.csv')
df = np.array(df)
np.random.shuffle(df)
df_test = df.T
Y_test = df_test[0]
X_test = df_test[1:785] 
X_test = X_test / 255.
W1 = W1[:, :783]


In [88]:
print(X_test.shape)  # should be (784, number of test samples)


(783, 28000)


In [89]:
Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X_test)
predictions = np.argmax(A2, axis=0)
accuracy = np.mean(predictions == Y_test) * 100
print(f"Test Accuracy: {accuracy:.2f}%")


Test Accuracy: 9.58%


Testing on validation dataset

In [133]:

df_val_dataset = df[0:1000].T
Y_val = df_val_dataset[0]
X_val = df_val_dataset[1:n]
X_val=X_val/255.


In [135]:
Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X_val)
def get_predictions(A2):
    return np.argmax(A2, axis=0)


def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size


In [136]:
Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X_val)
predictions = get_predictions(A2)
accuracy = get_accuracy(predictions, Y_val)
print(f"Validation Accuracy: {accuracy * 100:.2f}%")


[6 4 4 5 5 4 1 3 5 1 3 0 1 7 9 8 9 5 4 1 3 8 0 2 8 4 6 5 5 6 5 0 4 0 9 1 6
 6 7 4 2 0 0 3 9 6 3 3 7 6 9 1 7 7 1 3 8 5 4 5 1 8 3 2 0 2 9 9 9 4 7 3 2 9
 8 4 6 8 2 7 0 4 3 0 9 5 0 6 5 7 2 7 3 6 7 7 9 1 0 8 6 1 1 3 0 5 4 1 1 3 5
 0 0 4 0 4 3 9 1 5 1 2 1 8 2 4 5 4 5 5 6 4 9 9 2 1 7 2 8 1 1 6 4 4 9 4 2 5
 8 0 6 5 2 6 5 0 6 3 3 6 0 4 6 1 9 0 1 7 0 6 5 2 7 7 3 9 8 5 5 0 5 6 2 9 1
 7 4 1 6 4 2 1 7 1 9 6 9 8 8 8 6 9 6 3 9 0 0 2 3 5 7 8 7 7 8 7 8 4 7 2 8 9
 9 0 1 4 3 2 0 1 5 4 2 1 0 0 4 5 0 1 1 9 6 1 4 9 9 2 7 4 7 5 0 6 7 9 2 1 6
 5 1 7 1 3 2 4 9 3 3 9 3 4 6 2 5 1 6 4 6 1 9 4 4 8 0 2 7 3 0 2 4 0 8 9 3 1
 4 2 1 6 0 8 7 9 6 2 5 3 9 6 7 7 2 8 7 1 2 7 5 5 0 4 4 3 4 7 6 7 4 8 9 4 4
 2 7 9 2 3 3 2 7 0 5 3 6 1 1 1 2 5 1 0 7 1 6 9 0 9 5 1 3 4 9 0 0 3 9 3 5 8
 6 8 1 6 7 0 3 4 8 7 5 2 8 0 0 4 1 2 1 6 9 9 9 6 2 0 5 1 1 4 3 7 6 7 3 6 5
 9 4 6 1 2 4 8 7 1 1 5 3 9 4 2 1 9 3 9 4 5 5 6 1 8 2 0 9 4 4 4 4 6 7 0 3 4
 7 7 6 6 7 5 9 8 9 8 7 7 1 7 8 1 3 2 8 2 0 7 6 1 7 5 3 0 6 6 2 8 4 2 3 5 9
 8 5 4 7 4 7 8 5 3 6 5 2 